server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_iam
    username: user
    password: password
  jooq:
    sql-dialect: POSTGRES
  data:
    redis:
      host: localhost
      port: 16379
  modulith:
    detection-strategy: explicitly-annotated
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

logging:
  level:
    root: INFO
    com.myiam: DEBUG
  pattern:
    correlation: "[%X{traceId:-}] [%X{spanId:-}] "

jwt:
  key:
    rotation:
      cron: "0 0 1 1 * *"
    ttl: P35D

app:
  security:
    login-path: "/login"
  cache:
    auth:
      specs:
        jwk: "expireAfterWrite=1h,maximumSize=50"
        registered_client: "expireAfterWrite=10m,maximumSize=100"
        registered_client_id_map: "expireAfterWrite=10d,maximumSize=9999"
        user_claims: "expireAfterWrite=15m"

#ToDo: 敏感情報を別ファイルに移動する（ビルド流れ調整合わせて）
management:
  endpoints:
    web:
      exposure:
        include: beans,conditions